services:

  backend:
    image: blog-backend
    depends_on:
      - mongo
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://the_username:the_password@mongo:27017/the_database
      - PORT=3000
      - SECRET=supersecret

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./backend/mongodb/init.js:/docker-entrypoint-initdb.d/init.js
      - ./backend/mongodb/data:/data/db


  frontend:
    image: blog-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - frontend
      - backend
  